### ISSUE TITLE
Change the ascii method

### ISSUE THREAD

**Issue by retatu** [retatu/2-word-checker#1]
Improve the algorithm that converts to ascii. You can change the method to `ascii += (100.0 / bytes[i])*i` or another way.

**Comment by rodolfoberlezi** [comment]
[workchecker.zip](https://github.com/retatu/2-word-checker/files/2028370/workchecker.zip)

I did it. Sometimes it works very well, being even faster, but othertimes it does not find a solution.

**Comment by retatu** [comment]
Yes, it happens because we need more examples.

**Comment by retatu** [comment]
It was resolve by Rodolfo

**Comment by retatu** [comment]
Good for us.

*Matheus H. Rehbein*


*​Applied Computing Research Group - GCA*
*http://www.gca.unijui.edu.br <http://www.gca.unijui.edu.br>*

2018-05-22 17:07 GMT-03:00 Rodolfo Berlezi <notifications@github.com>:
